# Generated by Django 5.0.4 on 2024-04-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0002_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
