# Generated by Django 5.0.4 on 2024-04-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0003_alter_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.BigIntegerField(null=True),
        ),
    ]
